export const LOGGED_USER = 'LOGGED_USER';

export const NEW_USER_REGISTER = 'NEW_USER_REGISTER';

export const SIGNIN_USER = 'SIGNIN_USER';

export const SIGNOUT_USER = 'SIGNOUT_USER';

export const START_SESSION = 'START_SESSION';

export const CLOSE_SESSION = 'CLOSE_SESSION';

export const UNLOGGED_USER = 'UNLOGGED_USER';

export const LOAD_IMAGE = 'LOAD_IMAGE';

export const CLEAR_IMAGE = 'CLEAR_IMAGE';

export const LOAD_IMAGE_TO_UPLOAD = 'LOAD_IMAGE_TO_UPLOAD';

export const UNLOAD_IMAGE_TO_UPLOAD = 'UNLOAD_IMAGE_TO_UPLOAD';

export const PUBLISH_IMAGE = 'PUBLISH_IMAGE';

export const GET_PUBLICATIONS = 'GET_PUBLICATIONS';

export const LOAD_PUBLICATIONS_TO_STORE = 'LOAD_PUBLICATIONS_TO_STORE';

export const UNLOAD_PUBLICATIONS_TO_STORE = 'UNLOAD_PUBLICATIONS_TO_STORE';

export const LOAD_AUTHORS_TO_STORE = 'LOAD_AUTHORS_TO_STORE';

export const UNLOAD_AUTHORS_TO_STORE = 'UNLOAD_AUTHORS_TO_STORE';

export const SUCCESS_PUBLISH = 'SUCCESS_PUBLISH'; 

export const UNSUCCESS_PUBLISH = 'UNSUCCESS_PUBLISH';

export const RESET_PUBLISH_STATE = 'RESET_PUBLISH_STATE';
